export default {
	alignment: {type: 'string', default: 'center'},
	backgroundColor: {type: 'string', default: 'rgba(0,0,0,0)'},
	color: {type: 'string', default: '#fff'},
	fog: {type: 'boolean', default: false},
	fontFamily: {type: 'string', default: 'sans-serif'},
	fontSize: {type: 'number', default: 1},
	fontStyle: {type: 'string', default: 'normal'},
	fontVariant: {type: 'string', default: 'normal'},
	fontWeight: {type: 'string', default: 'normal'},
	lineGap: {type: 'number', default: 0.25},
	opacity: {type: 'number', default: 1},
	padding: {type: 'number', default: 0.5},
	strokeColor: {type: 'string', default: '#fff'},
	strokeWidth: {type: 'number', default: 0},
	text: {type: 'string', default: ''},
	transparent: {type: 'boolean', default: true},
};
